name = "SeawaterPolynomials"
uuid = "d496a93d-167e-4197-9f49-d3af4ff8fe40"
authors = ["Climate Modeling Alliance and contributors"]
version = "0.3.2"

[compat]
julia = "^1"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Coverage"]
